metadata:
  description: "A canvas demo using the Mozilla animated clock canvas tutorial (0.9.14)"
  maximumVersion: "0.9.14"
  name: "examples/clock"

# No need for any instructions - we just copy the demo as is

